export const FALLBACK_SERVICES = [
  {
    id: "private-charter",
    title: "Private Helicopter Charter",
    slug: "helicopter-charter-nepal",
    shortDescription: "Arrange an aircraft around your route, group size, date, and operating requirements.",
    longDescription: "Private charter requests are planned around route feasibility, passenger and baggage details, aircraft availability, weather, and permissions. Submit the full requirement for an operational and commercial review.",
    seoDescription: "Request private helicopter charter in Nepal with route, aircraft availability, passenger requirements, and current fare confirmed directly.",
    seoTitle: null,
    icon: null,
    featuredImage: null,
    published: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  },
  {
    id: "shared-flights",
    title: "Shared Helicopter Flights",
    slug: "shared-helicopter-flights",
    shortDescription: "Request a seat on selected routes when compatible passengers and an operating departure are confirmed.",
    longDescription: "Shared flights combine compatible travelers on selected routes. No departure is guaranteed until passengers, aircraft, weather, route, permissions, and commercial terms are confirmed.",
    seoDescription: "Request a shared helicopter seat in Nepal and receive current availability and per-person fare information when a compatible departure is confirmed.",
    seoTitle: null,
    icon: null,
    featuredImage: null,
    published: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  },
  {
    id: "pokhara-service",
    title: "Pokhara Helicopter Service",
    slug: "pokhara-helicopter-service",
    shortDescription: "Plan scenic flights, mountain routes, pilgrimage travel, and private charter requests from Pokhara.",
    longDescription: "Pokhara flight requests are reviewed against the intended route, passenger and baggage details, current aircraft position, weather, permissions, and the final operating plan. Share your date range and route for a current written quote.",
    seoDescription: "Request helicopter service from Pokhara for scenic flights, Annapurna routes, pilgrimage travel, and private charter planning.",
    seoTitle: null,
    icon: null,
    featuredImage: "/images/campaign/annapurna-helicopter.jpg",
    ogImage: "/images/campaign/annapurna-helicopter.jpg",
    noindex: false,
    published: true,
    createdAt: new Date("2026-08-12T00:00:00.000Z"),
    updatedAt: new Date("2026-08-12T00:00:00.000Z")
  },
  {
    id: "custom-private-flight",
    title: "Custom Private Helicopter Flight",
    slug: "luxury-helicopter-tour-nepal",
    shortDescription: "Request a private route around your group, timing, destination, and practical travel requirements.",
    longDescription: "A custom private flight starts with the route, date range, passenger weights, luggage or equipment, landing request, and ground arrangements. Availability and the final service basis are confirmed in writing with the operating details and quote.",
    seoDescription: "Request a custom private helicopter flight in Nepal with routing, passengers, timing, and current operating details reviewed directly.",
    seoTitle: null,
    icon: null,
    featuredImage: "/images/campaign/sharing-heli-hero.jpg",
    ogImage: "/images/campaign/sharing-heli-hero.jpg",
    noindex: false,
    published: true,
    createdAt: new Date("2026-08-12T00:00:00.000Z"),
    updatedAt: new Date("2026-08-12T00:00:00.000Z")
  },
  {
    id: "pilgrimage",
    title: "Pilgrimage Flight Planning",
    slug: "muktinath-helicopter-tour-nepal",
    shortDescription: "Coordinate time-sensitive pilgrimage travel with clear route and weather guidance.",
    longDescription: "Pilgrimage flight requests are reviewed for date, passenger needs, route access, aircraft availability, and weather. Departure and landing details are confirmed before travel.",
    seoDescription: "Plan a Muktinath pilgrimage helicopter request from Pokhara with current routing and operating information.",
    seoTitle: null,
    icon: null,
    featuredImage: null,
    published: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  },
  {
    id: "urgent-coordination",
    title: "Emergency Flight Coordination",
    slug: "emergency-helicopter-rescue-nepal",
    shortDescription: "Relay urgent transport requirements subject to aircraft, weather, permission, and crew confirmation.",
    longDescription: "Sharing Heli can help coordinate urgent flight requests with available operators. This is not a guaranteed dispatch service; feasibility depends on location, weather, daylight, aircraft, permissions, and the operator's assessment.",
    seoDescription: "Request urgent helicopter flight coordination in Nepal, subject to aircraft, weather, permissions, daylight, and operator confirmation.",
    seoTitle: null,
    icon: null,
    featuredImage: null,
    published: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  }
];

export const FALLBACK_TOURS = [
  {
    id: "everest-region",
    title: "Everest Region Helicopter Tour",
    slug: "everest-base-camp-helicopter-tour-nepal",
    duration: "Timing on request",
    currency: "USD",
    priceMode: "LIVE_QUOTE",
    sharedPriceFrom: null,
    privateCharterPrice: null,
    priceValidFrom: null,
    priceValidUntil: null,
    lastVerifiedAt: null,
    pricingNote: null,
    sharedAvailable: true,
    privateAvailable: true,
    departureCity: "Kathmandu",
    images: ["/images/campaign/everest-helicopter.jpg"],
    seoDescription: "A weather-led flight into the Everest region, with routing and any landing point confirmed for the day.",
    highlights: "Everest region aerial views with the route selected for the day's operating conditions.",
    itinerary: "Departure and return points are confirmed before travel. Routing and any landing stop depend on current conditions and the operating crew.",
    inclusions: "Flight coordination and the inclusions stated in the final written quote.",
    exclusions: "Items not listed in the final quote, personal expenses, and travel insurance.",
    operationalNotice: "No landing at Everest Base Camp or Kala Patthar is promised.",
    priceFrom: null,
    ctaLabel: null,
    ctaHref: null,
    seoTitle: null,
    published: true,
    featured: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  },
  {
    id: "annapurna-region",
    title: "Annapurna Region Helicopter Tour",
    slug: "annapurna-base-camp-helicopter-tour-nepal",
    duration: "Timing on request",
    currency: "USD",
    priceMode: "LIVE_QUOTE",
    sharedPriceFrom: null,
    privateCharterPrice: null,
    priceValidFrom: null,
    priceValidUntil: null,
    lastVerifiedAt: null,
    pricingNote: null,
    sharedAvailable: true,
    privateAvailable: true,
    departureCity: "Pokhara",
    images: ["/images/campaign/annapurna-helicopter.jpg"],
    seoDescription: "A Pokhara departure toward the Annapurna range, planned around visibility, weather, and route access.",
    highlights: "Annapurna region aerial views with routing confirmed against current conditions.",
    itinerary: "Pokhara departure, route approved for the flight, and return. Any landing is confirmed before travel.",
    inclusions: "Flight coordination and the inclusions stated in the final written quote.",
    exclusions: "Items not listed in the final quote, personal expenses, and travel insurance.",
    operationalNotice: "Route and any landing remain subject to weather, passenger weight, permissions, and operator approval.",
    priceFrom: null,
    ctaLabel: null,
    ctaHref: null,
    seoTitle: null,
    published: true,
    featured: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  },
  {
    id: "muktinath",
    title: "Muktinath Helicopter Tour",
    slug: "muktinath-helicopter-tour-nepal",
    duration: "Timing on request",
    currency: "USD",
    priceMode: "LIVE_QUOTE",
    sharedPriceFrom: null,
    privateCharterPrice: null,
    priceValidFrom: null,
    priceValidUntil: null,
    lastVerifiedAt: null,
    pricingNote: null,
    sharedAvailable: true,
    privateAvailable: true,
    departureCity: "Pokhara",
    images: ["/images/campaign/muktinath-helicopter.jpg"],
    seoDescription: "Pilgrimage-focused flight coordination with timing and landing conditions confirmed before departure.",
    highlights: "Muktinath pilgrimage flight planning from Pokhara with current route information.",
    itinerary: "Departure, any approved landing and ground time, and return are detailed in the final operational confirmation.",
    inclusions: "Flight coordination and the inclusions stated in the final written quote.",
    exclusions: "Items not listed in the final quote, personal expenses, and travel insurance.",
    operationalNotice: "Flights operate only when weather, aircraft availability, and landing conditions permit.",
    priceFrom: null,
    ctaLabel: null,
    ctaHref: null,
    seoTitle: null,
    published: true,
    featured: true,
    createdAt: new Date("2026-08-09T00:00:00.000Z"),
    updatedAt: new Date("2026-08-09T00:00:00.000Z")
  }
];

export const FALLBACK_DESTINATIONS = [
  {
    id: "annapurna",
    title: "Annapurna Region",
    description: "Pokhara-based scenic routes toward the Annapurna range and surrounding valleys.",
    image: "/images/campaign/annapurna-helicopter.jpg",
    order: 1,
    visible: true
  },
  {
    id: "everest",
    title: "Everest Region",
    description: "High-altitude Himalayan flights with routes determined by the day's conditions.",
    image: "/images/campaign/everest-helicopter.jpg",
    order: 2,
    visible: true
  },
  {
    id: "pilgrimage",
    title: "Pilgrimage Routes",
    description: "Muktinath and other requested routes coordinated around access and weather.",
    image: "/images/campaign/muktinath-helicopter.jpg",
    order: 3,
    visible: true
  }
];
